local awful = require("awful")

awful.spawn("sh /home/frey/.config/polybar/launch.sh")
awful.spawn("albert")
awful.spawn("nitrogen --restore")
awful.spawn("copyq")
--awful.spawn("xrdb /home/frey/.Xresources")
awful.spawn("killall picom")
awful.spawn("picom")
awful.spawn("flameshot")
awful.util.spawn_with_shell("bash -c 'killall -9 redshift ; redshift -x && redshift'")
